[theme]
primaryColor="#0078D4"       # Azul profesional
backgroundColor="#FFFFFF"    # Fondo blanco
secondaryBackgroundColor="#F8F9FA"  # Gris muy claro
textColor="#212529"          # Negro suave para mejor legibilidad
font="sans serif"            # Fuente sans serif
